import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const html = fs.readFileSync(path.join(rootDir, "outputs/web_prototype/easy_exam_automation.html"), "utf8");

test("hidden views cannot be overridden by component display styles", () => {
  assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important;?\s*\}/);
});

test("navigation orders project management, exam list, then auto configuration", () => {
  const nav = html.slice(html.indexOf('<nav class="nav"'), html.indexOf("</nav>"));
  const projectIndex = nav.indexOf('id="projectNavBtn"');
  const examIndex = nav.indexOf('id="examNavBtn"');
  const autoIndex = nav.indexOf('id="autoNavItem"');
  assert.ok(projectIndex >= 0 && examIndex >= 0 && autoIndex >= 0);
  assert.ok(projectIndex < examIndex && examIndex < autoIndex);
});

test("URL page layout replaces shared showView content switching", () => {
  assert.ok(html.includes('import { createRouter } from "/web/router.mjs"'));
  assert.ok(html.includes("ProjectListPage({ root: projectManagementView"));
  assert.ok(html.includes("ExamListPage({ root: examListView"));
  assert.ok(html.includes("RequirementListPage({ root: requirementsView"));
  assert.ok(html.includes("RequirementDetailPage({ root: requirementDetailView"));
  assert.ok(html.includes('staticPage("wechat-collector", wechatCollectorView, loadWechatCollector'));
  assert.equal(html.includes("function showView"), false);
  assert.equal(html.includes("syncActiveNavByScroll"), false);
});

test("requirement center renders list and detail surfaces", () => {
  assert.ok(html.includes('id="requirementsList"'));
  assert.ok(html.includes('id="requirementDetailView"'));
  assert.ok(html.includes('id="requirementClarificationBtn"'));
  assert.ok(html.includes('id="requirementClarificationQuestions"'));
  assert.ok(html.includes('id="requirementClarificationPrompt"'));
  assert.ok(html.includes('id="requirementReviewedBtn"'));
  assert.ok(html.includes('id="requirementMarkReadyBtn"'));
  assert.ok(html.includes('id="requirementLinkTaskBtn"'));
  assert.ok(html.includes('id="requirementTimeline"'));
  assert.ok(html.includes('id="requirementVersions"'));
  assert.ok(html.includes('id="requirementChanges"'));
  assert.ok(html.includes('id="requirementSource"'));
  assert.ok(html.includes('id="requirementAuditMessage"'));
  assert.ok(html.includes("ready_for_manual_execution"));
  assert.ok(html.includes("renderRequirementChangeRequests"));
  assert.ok(html.includes('data-change-action="accept"'));
  assert.ok(html.includes('data-change-action="reject"'));
  assert.ok(html.includes("/change-requests/"));
  assert.ok(html.includes("change_request_accepted"));
  assert.ok(html.includes("change_request_rejected"));
  assert.ok(html.includes("发给客户的补充问题"));
  assert.ok(html.includes("formatRequirementEvent"));
  assert.ok(html.includes("parseRequirementSource"));
  assert.ok(html.includes("微信群"));
  assert.ok(html.includes("采集时间"));
  assert.equal(html.includes("JSON.stringify(item.payload || {})"), false);
});

test("WeChat collector page renders config and scheduler status surfaces", () => {
  assert.ok(html.includes('id="wechatCollectorNavBtn"'));
  assert.ok(html.includes('id="wechatCollectorView"'));
  assert.ok(html.includes('id="wechatCollectorReadiness"'));
  assert.ok(html.includes('id="wechatCollectorGoLive"'));
  assert.ok(html.includes('id="wechatCollectorConfig"'));
  assert.ok(html.includes('id="wechatCollectorConfigBackups"'));
  assert.ok(html.includes('id="wechatCollectorStatus"'));
  assert.ok(html.includes('id="wechatCollectorHistory"'));
  assert.ok(html.includes('id="wechatCollectorPreflight"'));
  assert.ok(html.includes('id="wechatAttachmentScan"'));
  assert.ok(html.includes('id="wechatPipelineSmoke"'));
  assert.ok(html.includes('id="wechatCollectorLogs"'));
  assert.ok(html.includes('id="wechatCollectorService"'));
  assert.ok(html.includes('id="wechatCollectorScheduler"'));
  assert.ok(html.includes('id="wechatCollectorRequirementCenter"'));
  assert.ok(html.includes('id="installWechatCollectorServiceBtn"'));
  assert.ok(html.includes('id="uninstallWechatCollectorServiceBtn"'));
  assert.ok(html.includes('id="installWechatCollectorSchedulerBtn"'));
  assert.ok(html.includes('id="uninstallWechatCollectorSchedulerBtn"'));
  assert.ok(html.includes('id="installWechatCollectorAutomationBtn"'));
  assert.ok(html.includes('id="uninstallWechatCollectorAutomationBtn"'));
  assert.ok(html.includes('id="refreshWechatCollectorBtn"'));
  assert.ok(html.includes('id="dryRunWechatCollectorBtn"'));
  assert.ok(html.includes('id="runWechatCollectorOnceBtn"'));
  assert.ok(html.includes('id="scanWechatAttachmentsBtn"'));
  assert.ok(html.includes('id="wechatAttachmentRootInput"'));
  assert.ok(html.includes('id="wechatAttachmentModifiedSinceInput"'));
  assert.ok(html.includes('id="wechatAttachmentMaxFilesInput"'));
  assert.ok(html.includes('id="wechatAttachmentPreviewCharsInput"'));
  assert.ok(html.includes('id="runWechatPipelineSmokeBtn"'));
  assert.ok(html.includes('id="addWechatGroupBtn"'));
  assert.ok(html.includes('id="saveWechatCollectorConfigBtn"'));
  assert.ok(html.includes('data-wechat-action="remove"'));
  assert.ok(html.includes('data-wechat-action="run-once"'));
  assert.ok(html.includes("renderWechatCollectorReadiness"));
  assert.ok(html.includes("微信群配置"));
  assert.ok(html.includes("renderWechatCollectorGoLive"));
  assert.ok(html.includes("setWechatCollectorInstallAvailability"));
  assert.ok(html.includes("installWechatCollectorSchedulerBtn.disabled = !available;"));
  assert.ok(html.includes("installWechatCollectorAutomationBtn.disabled = !available;"));
  assert.ok(html.includes('const missingLabels = checks.filter((item) => !item.ok).map((item) => item.label);'));
  assert.ok(html.includes("上线门槛"));
  assert.ok(html.includes("配置合法"));
  assert.ok(html.includes("config_valid"));
  assert.ok(html.includes('readinessChecks.find((item) => item.key === "pipeline_smoke")'));
  assert.ok(html.includes("const smokeOk = Boolean(smokeCheck.ok);"));
  assert.equal(html.includes("const smokeOk = Boolean(statusData.pipelineSmoke?.ok);"), false);
  assert.ok(html.includes('readinessChecks.find((item) => item.key === "requirement_push")'));
  assert.ok(html.includes("const realPushOk = Boolean(realPushCheck.ok);"));
  assert.equal(html.includes('latestRunGroups.filter((group) => group.status === "pushed")'), false);
  assert.ok(html.includes("真实微信试跑"));
  assert.ok(html.includes("定时已安装并加载"));
  assert.ok(html.includes("renderWechatCollectorLogs"));
  assert.ok(html.includes("renderWechatCollectorScheduler"));
  assert.ok(html.includes("renderWechatCollectorService"));
  assert.ok(html.includes("手动服务可达"));
  assert.ok(html.includes("LaunchAgent 常驻"));
  assert.ok(html.includes("不会自动下载群文件"));
  assert.ok(html.includes("renderWechatCollectorRequirementCenter"));
  assert.ok(html.includes("renderWechatCollectorRunGroups"));
  assert.ok(html.includes("renderWechatCollectorHistory"));
  assert.ok(html.includes('const fallbackStatus = item.status || "unknown";'));
  assert.ok(html.includes('const statusText = groups.length ? groupStatusText : wechatCollectorStatusLabel(fallbackStatus);'));
  assert.ok(html.includes('const failed = fallbackStatus === "failed" || fallbackStatus === "skipped"'));
  assert.ok(html.includes("运行历史"));
  assert.ok(html.includes("renderWechatCollectorConfig(groups, statusData.groups || [])"));
  assert.ok(html.includes("renderWechatCollectorConfigBackups(statusData.configBackups"));
  assert.ok(html.includes("最近配置备份"));
  assert.ok(html.includes('data-wechat-action="restore-config"'));
  assert.ok(html.includes("/api/wechat-collector/config/restore"));
  assert.ok(html.includes("restoreWechatCollectorConfigBackup"));
  assert.ok(html.includes("latestStatus"));
  assert.ok(html.includes("status.latestError ? `错误：${status.latestError}` : \"\""));
  assert.ok(html.includes("checkpointUpdatedAt"));
  assert.ok(html.includes("下次运行"));
  assert.ok(html.includes("renderWechatCollectorPreflight"));
  assert.ok(html.includes("renderWechatAttachmentScanSummary(statusData.attachmentScan"));
  assert.ok(html.includes("最近只读扫描"));
  assert.ok(html.includes("renderWechatPipelineSmoke(statusData.pipelineSmoke || {})"));
  assert.ok(html.includes("const freshnessText = result.ok ? (result.fresh ? \"有效\" : (result.stale ? \"已过期\" : \"待确认\")) : \"未通过\";"));
  assert.ok(html.includes("完成：${formatTaskTime(result.finishedAt)}"));
  assert.ok(html.includes("skipped_interval"));
  assert.ok(html.includes("no_new_messages"));
  assert.ok(html.includes("captureMode"));
  assert.ok(html.includes("screenshotPath"));
  assert.ok(html.includes("captureRect"));
  assert.ok(html.includes("截图区域：${safeText(group.captureRect)}"));
  assert.ok(html.includes("ocrCommand"));
  assert.ok(html.includes("nextRunAt"));
  assert.ok(html.includes("附件候选：${Number(group.attachmentCandidateCount || 0)} · 已关联：${Number(group.attachmentCount || 0)}"));
  assert.ok(html.includes("附件过滤"));
  assert.ok(html.includes("installWechatCollectorService"));
  assert.ok(html.includes("uninstallWechatCollectorService"));
  assert.ok(html.includes("installWechatCollectorAutomation"));
  assert.ok(html.includes("uninstallWechatCollectorAutomation"));
  assert.ok(html.includes("confirmWechatSideEffect"));
  assert.ok(html.includes("会激活微信"));
  assert.ok(html.includes("LaunchAgent"));
  assert.ok(html.includes("runWechatCollectorOnce"));
  assert.ok(html.includes("runWechatCollectorGroupOnce"));
  assert.ok(html.includes("groupName"));
  assert.ok(html.includes("await loadWechatCollector()"));
  assert.ok(html.includes("dryRunWechatCollector"));
  assert.ok(html.includes("scanWechatAttachments"));
  assert.ok(html.includes("buildWechatAttachmentScanUrl"));
  assert.ok(html.includes('params.set("root"'));
  assert.ok(html.includes('params.set("modifiedSince"'));
  assert.ok(html.includes('params.set("maxFiles"'));
  assert.ok(html.includes('params.set("previewChars"'));
  assert.ok(html.includes("runWechatPipelineSmoke"));
  assert.ok(html.includes("/api/wechat-collector/pipeline-smoke-test"));
  assert.ok(html.includes("fetchWechatPipelineSmoke"));
  assert.ok(html.includes("return { httpOk: response.ok, status: response.status, data };"));
  assert.ok(html.includes("renderWechatPipelineSmoke(result.data?.result || { ok: false, error: result.data?.error ||"));
  assert.ok(html.includes("/api/wechat-collector/attachments/scan"));
  assert.ok(html.includes("/api/wechat-collector/dry-run"));
  assert.ok(html.includes("installWechatCollectorScheduler"));
  assert.ok(html.includes("uninstallWechatCollectorScheduler"));
  assert.ok(html.includes("collectWechatCollectorConfig"));
  assert.ok(html.includes("validateWechatCollectorConfig"));
  assert.ok(html.includes("wechatIntervalInputValue"));
  assert.equal(html.includes("Number(group.interval_minutes || 15)"), false);
  assert.equal(html.includes('value("interval_minutes") || "15"'), false);
  assert.ok(html.includes("采集间隔必须是大于等于 1 的整数"));
  assert.ok(html.includes("微信群名称重复"));
  assert.ok(html.includes("removeWechatCollectorRow"));
  assert.ok(html.includes("/api/wechat-collector/config"));
  assert.ok(html.includes("/api/wechat-collector/status"));
  assert.ok(html.includes('method: "PUT"'));
  assert.ok(html.includes("result.backupPath"));
  assert.ok(html.includes("已备份上一版配置"));
  assert.ok(html.includes("await loadWechatCollector()"));
  assert.ok(html.includes("配置已保存，正在刷新状态"));
});
