import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const html = fs.readFileSync(path.join(rootDir, "outputs/web_prototype/easy_exam_automation.html"), "utf8");

test("hidden views cannot be overridden by component display styles", () => {
  assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important;?\s*\}/);
});

test("navigation orders project management, exam list, then auto configuration", () => {
  const nav = html.slice(html.indexOf('<nav class="nav"'), html.indexOf("</nav>"));
  const projectIndex = nav.indexOf('id="projectNavBtn"');
  const examIndex = nav.indexOf('id="examNavBtn"');
  const autoIndex = nav.indexOf('id="autoNavItem"');
  assert.ok(projectIndex >= 0 && examIndex >= 0 && autoIndex >= 0);
  assert.ok(projectIndex < examIndex && examIndex < autoIndex);
});

test("URL page layout replaces shared showView content switching", () => {
  assert.ok(html.includes('import { createRouter } from "/web/router.mjs"'));
  assert.ok(html.includes("ProjectListPage({ root: projectManagementView"));
  assert.ok(html.includes("ExamListPage({ root: examListView"));
  assert.ok(html.includes("RequirementListPage({ root: requirementsView"));
  assert.ok(html.includes("RequirementDetailPage({ root: requirementDetailView"));
  assert.ok(html.includes('staticPage("wechat-collector", wechatCollectorView, loadWechatCollector'));
  assert.equal(html.includes("function showView"), false);
  assert.equal(html.includes("syncActiveNavByScroll"), false);
});

test("requirement center renders list and detail surfaces", () => {
  assert.ok(html.includes('id="requirementsList"'));
  assert.ok(html.includes('id="requirementWorkQueueFilters"'));
  assert.ok(html.includes("需求处理工作台"));
  assert.ok(html.includes("renderRequirementWorkQueueFilters"));
  assert.ok(html.includes("requirementNextAction"));
  assert.ok(html.includes("data-requirement-filter"));
  assert.ok(html.includes("有待处理变更"));
  assert.ok(html.includes("处理变更"));
  assert.ok(html.includes("审核需求"));
  assert.ok(html.includes('id="requirementDetailView"'));
  assert.ok(html.includes('id="requirementNextStep"'));
  assert.ok(html.includes("当前处理建议"));
  assert.ok(html.includes("renderRequirementNextStep"));
  assert.ok(html.includes("优先处理客户变更"));
  assert.ok(html.includes("生成客户补充话术"));
  assert.ok(html.includes("标记客户已确认，可进入执行"));
  assert.ok(html.includes("<details open><summary>2. 当前可执行操作</summary>"));
  assert.ok(html.includes("<details><summary>3. 变更与确认记录</summary>"));
  assert.ok(html.includes("<details><summary>4. 审计记录</summary>"));
  assert.ok(html.includes('id="requirementClarificationBtn"'));
  assert.ok(html.includes('id="requirementClarificationQuestions"'));
  assert.ok(html.includes('id="requirementClarificationPrompt"'));
  assert.ok(html.includes('id="requirementReviewedBtn"'));
  assert.ok(html.includes('id="requirementMarkReadyBtn"'));
  assert.ok(html.includes('id="requirementLinkTaskBtn"'));
  assert.ok(html.includes('id="requirementTimeline"'));
  assert.ok(html.includes('id="requirementVersions"'));
  assert.ok(html.includes('id="requirementChanges"'));
  assert.ok(html.includes('id="requirementAnalysisCandidates"'));
  assert.ok(html.includes('id="requirementSource"'));
  assert.ok(html.includes('id="requirementAuditMessage"'));
  assert.ok(html.includes("ready_for_manual_execution"));
  assert.ok(html.includes("renderRequirementChangeRequests"));
  assert.ok(html.includes('data-change-action="accept"'));
  assert.ok(html.includes('data-change-action="reject"'));
  assert.ok(html.includes("/change-requests/"));
  assert.ok(html.includes("change_request_accepted"));
  assert.ok(html.includes("change_request_rejected"));
  assert.ok(html.includes("formatRequirementChangeFields"));
  assert.ok(html.includes("formatRequirementChangeRecord"));
  assert.ok(html.includes("isDisplayableRequirementChangeField"));
  assert.ok(html.includes('["watermark_enabled", "copy_forbidden"].includes(field)'));
  assert.ok(html.includes("采纳并生成新版本"));
  assert.ok(html.includes("驳回此次变更"));
  assert.ok(html.includes("采纳后会生成新的需求版本；驳回后不会修改当前需求。"));
  assert.ok(html.includes("0. 解析结果确认"));
  assert.ok(html.includes("规则解析和 LLM 候选解析都会在这里展示"));
  assert.ok(html.includes("renderRequirementAnalysisCandidates"));
  assert.ok(html.includes("latestAnalysisCandidateEvent"));
  assert.ok(html.includes("LLM 候选"));
  assert.ok(html.includes("规则与 LLM 冲突"));
  assert.ok(html.includes("发给客户的补充问题"));
  assert.ok(html.includes("1. 核对需求内容"));
  assert.ok(html.includes("先看最新需求、缺失项和原始来源"));
  assert.equal(html.includes("2. 人工审核处理"), false);
  assert.ok(html.includes("微信群模式下，审核动作只处理需求单状态，不会反向操作微信群"));
  assert.ok(html.includes("要求客户补充：信息不完整时生成可复制的话术"));
  assert.ok(html.includes("内部审核通过，待客户确认：内容完整但还需要客户最终确认"));
  assert.ok(html.includes("标记可进入执行：客户确认后交给执行侧创建考试任务"));
  assert.ok(html.includes("关联执行任务编号：记录后续创建出的考试任务，便于从需求追踪到执行结果"));
  assert.ok(html.includes("3. 变更与确认记录"));
  assert.ok(html.includes("4. 审计记录"));
  assert.ok(html.includes("formatRequirementEvent"));
  assert.ok(html.includes("parseRequirementSource"));
  assert.ok(html.includes("微信群"));
  assert.ok(html.includes("采集时间"));
  assert.equal(html.includes("JSON.stringify(item.payload || {})"), false);
  assert.equal(html.includes("JSON.stringify(item.changes || {})"), false);
});

test("WeChat collector page renders config and scheduler status surfaces", () => {
  assert.ok(html.includes('id="wechatCollectorNavBtn"'));
  assert.ok(html.includes('id="systemConfigNavBtn"'));
  assert.ok(html.includes('id="wechatCollectorView"'));
  assert.ok(html.includes('id="systemConfigView"'));
  assert.ok(html.includes('id="wechatCollectorReadiness"'));
  assert.ok(html.includes('id="wechatCollectorGoLive"'));
  assert.ok(html.includes('id="wechatCollectorConfig"'));
  assert.ok(html.includes('id="wechatCollectorConfigBackups"'));
  assert.ok(html.includes('id="wechatCollectorStatus"'));
  assert.ok(html.includes('id="wechatCollectorHistory"'));
  assert.ok(html.includes('id="wechatCollectorPreflight"'));
  assert.ok(html.includes('id="wechatPipelineSmoke"'));
  assert.ok(html.includes('id="wechatCollectorLogs"'));
  assert.ok(html.includes('id="wechatCollectorService"'));
  assert.ok(html.includes('id="wechatCollectorScheduler"'));
  assert.ok(html.includes('id="wechatCollectorRequirementCenter"'));
  assert.ok(html.includes('id="installWechatCollectorServiceBtn"'));
  assert.ok(html.includes('id="uninstallWechatCollectorServiceBtn"'));
  assert.ok(html.includes('id="installWechatCollectorSchedulerBtn"'));
  assert.ok(html.includes('id="uninstallWechatCollectorSchedulerBtn"'));
  assert.ok(html.includes('id="installWechatCollectorAutomationBtn"'));
  assert.ok(html.includes('id="uninstallWechatCollectorAutomationBtn"'));
  assert.ok(html.includes('id="refreshWechatCollectorBtn"'));
  assert.ok(html.includes('id="dryRunWechatCollectorBtn"'));
  assert.ok(html.includes('id="runWechatCollectorOnceBtn"'));
  assert.ok(html.includes('id="runWechatPipelineSmokeBtn"'));
  assert.ok(html.includes('id="addWechatGroupBtn"'));
  assert.equal(html.includes('id="saveWechatCollectorConfigBtn"'), false);
  assert.ok(html.includes('data-wechat-action="remove"'));
  assert.ok(html.includes('data-wechat-action="run-once"'));
  assert.ok(html.includes("renderWechatCollectorReadiness"));
  assert.ok(html.includes("微信群配置"));
  assert.ok(html.includes("1. 配置微信群"));
  assert.ok(html.includes("采集边界：可见群聊 OCR · 需求中心人工确认 · 已下载附件按本群可见文件名关联 · 不自动下载群文件"));
  assert.equal(html.includes("<h2 class=\"panel-title\">当前能力</h2>"), false);
  assert.ok(html.includes("每个微信群独立保存设置"));
  assert.equal(html.includes(">保存微信群配置<"), false);
  assert.ok(html.includes("wechat-group-card"));
  assert.ok(html.includes("wechat-group-summary"));
  assert.ok(html.includes("#wechatCollectorConfig"));
  assert.ok(html.includes("min-height: 0"));
  assert.ok(html.includes("max-height: 720px"));
  assert.ok(html.includes("项目：${safeText(group.project_name || \"未填写项目\")}"));
  assert.ok(html.includes("关联需求单编号"));
  assert.ok(html.includes("可留空。填入后，本群后续采集和变更会归到这张需求单；不填则首次有效采集时新建需求。"));
  assert.ok(html.includes('data-wechat-field="requirement_request_id"'));
  assert.ok(html.includes("保存本群设置"));
  assert.ok(html.includes('data-wechat-action="save-group"'));
  assert.ok(html.includes("群设置操作"));
  assert.equal(html.includes("<details><summary>群设置操作</summary>"), false);
  assert.ok(html.includes("<details><summary>高级：配置备份与恢复</summary>"));
  assert.ok(html.includes("<details><summary>3. 排障日志</summary>"));
  assert.ok(html.includes("最近运行摘要"));
  assert.ok(html.includes("只保留最近摘要，详细排障看群卡片或日志"));
  assert.equal(html.includes("<h2 class=\"panel-title\">配置备份与恢复</h2>"), false);
  assert.ok(html.includes("任务执行状态"));
  assert.ok(html.includes("需求更新记录"));
  assert.ok(html.includes("renderWechatGroupRequirementTimeline"));
  assert.ok(html.includes("renderWechatGroupRequirementUpdates"));
  assert.ok(html.includes("renderWechatGroupRequirementChanges"));
  assert.ok(html.includes("采集运行记录"));
  assert.ok(html.includes("客户变更记录"));
  assert.ok(html.includes("查看需求单详情"));
  assert.ok(html.includes('<h2 class="panel-title">需求更新记录</h2></div><div class="view-actions">${renderWechatRequirementDetailButton(effectiveRequestId)}</div>'));
  assert.equal(html.includes('const actions = `<div class="view-actions" style="margin-top:10px;"><button class="btn" data-wechat-action="open-requirement"'), false);
  assert.ok(html.includes("字段变更"));
  assert.ok(html.includes("本群已关联需求单，可在这里核对最近客户变更。"));
  assert.equal(html.includes("<h2 class=\"panel-title\">关联需求字段变更</h2>"), false);
  assert.ok(html.includes("messageCount"));
  assert.ok(html.includes("changeCount"));
  assert.ok(html.includes("1. 初始化验证"));
  assert.ok(html.includes("环境预检"));
  assert.ok(html.includes("立即采集"));
  assert.ok(html.includes("每个启用群上线前都需要在配置表对应行执行“立即采集本群”"));
  assert.ok(html.includes("识别到新需求或变更时会推送需求中心并更新 checkpoint"));
  assert.ok(html.includes("2. 上线自动采集"));
  assert.ok(html.includes("上线前必须完成"));
  assert.ok(html.includes("3. 高级维护"));
  assert.ok(html.includes("renderWechatCollectorGoLive"));
  assert.ok(html.includes("setWechatCollectorInstallAvailability"));
  assert.ok(html.includes("installWechatCollectorSchedulerBtn.disabled = !available;"));
  assert.ok(html.includes("installWechatCollectorAutomationBtn.disabled = !available;"));
  assert.ok(html.includes('const missingLabels = checks.filter((item) => !item.ok).map((item) => item.label);'));
  assert.ok(html.includes("上线前必须完成"));
  assert.ok(html.includes("配置合法"));
  assert.ok(html.includes("config_valid"));
  assert.ok(html.includes('readinessChecks.find((item) => item.key === "pipeline_smoke")'));
  assert.ok(html.includes("const smokeOk = Boolean(smokeCheck.ok);"));
  assert.equal(html.includes("const smokeOk = Boolean(statusData.pipelineSmoke?.ok);"), false);
  assert.ok(html.includes('readinessChecks.find((item) => item.key === "requirement_push")'));
  assert.ok(html.includes("const realPushOk = Boolean(realPushCheck.ok);"));
  assert.equal(html.includes('latestRunGroups.filter((group) => group.status === "pushed")'), false);
  assert.ok(html.includes("真实微信试跑"));
  assert.ok(html.includes("立即采集本群"));
  assert.ok(html.includes("定时已安装并加载"));
  assert.ok(html.includes("renderWechatCollectorLogs"));
  assert.ok(html.includes("renderWechatCollectorScheduler"));
  assert.ok(html.includes("renderWechatCollectorService"));
  assert.ok(html.includes("手动服务可达"));
  assert.ok(html.includes("LaunchAgent 常驻"));
  assert.ok(html.includes("不自动下载群文件"));
  assert.ok(html.includes("renderWechatCollectorRequirementCenter"));
  assert.ok(html.includes("renderWechatCollectorRunGroups"));
  assert.ok(html.includes("renderWechatCollectorHistory"));
  assert.ok(html.includes('const fallbackStatus = item.status || "unknown";'));
  assert.ok(html.includes('const statusText = groups.length ? groupStatusText : wechatCollectorStatusLabel(fallbackStatus);'));
  assert.ok(html.includes('const failed = fallbackStatus === "failed" || fallbackStatus === "skipped"'));
  assert.ok(html.includes("运行历史"));
  assert.ok(html.includes("taskViewState.wechatGroupStatuses = statusData.groups || []"));
  assert.ok(html.includes("renderWechatCollectorConfig(groups, taskViewState.wechatGroupStatuses, taskViewState.wechatHistory)"));
  assert.ok(html.includes("renderWechatCollectorConfigBackups(statusData.configBackups"));
  assert.ok(html.includes("配置备份与恢复"));
  assert.ok(html.includes('data-wechat-action="restore-config"'));
  assert.ok(html.includes("/api/wechat-collector/config/restore"));
  assert.ok(html.includes("restoreWechatCollectorConfigBackup"));
  assert.ok(html.includes("latestStatus"));
  assert.ok(html.includes("status.latestError ? `错误：${status.latestError}` : \"\""));
  assert.ok(html.includes("checkpointUpdatedAt"));
  assert.ok(html.includes("下次运行"));
  assert.ok(html.includes("renderWechatCollectorPreflight"));
  assert.equal(html.includes("附件扫描排障"), false);
  assert.equal(html.includes("扫描已下载文件"), false);
  assert.ok(html.includes("本群附件"));
  assert.ok(html.includes("本群最近一次采集未关联已下载附件"));
  assert.ok(html.includes('data-wechat-action="show-attachments"'));
  assert.ok(html.includes("系统配置"));
  assert.ok(html.includes("微信采集配置"));
  assert.ok(html.includes('id="wechatCollectorLaunchSummary"'));
  assert.ok(html.includes("微信采集上线状态"));
  assert.ok(html.includes("renderWechatCollectorLaunchSummary"));
  assert.ok(html.includes("上线前检查"));
  assert.ok(html.includes("检查本机采集环境"));
  assert.ok(html.includes("去微信采集页逐群验证"));
  assert.ok(html.includes("批量真实采集所有启用群"));
  assert.ok(html.includes("<details><summary>高级操作：批量真实采集</summary>"));
  assert.ok(html.includes("<details><summary>高级维护：服务与定时任务</summary>"));
  assert.ok(html.includes("一般不用改 Endpoint"));
  assert.ok(html.includes("清空已保存密钥"));
  assert.ok(html.includes("LLM 候选解析"));
  assert.equal(html.includes("cc-connect 新消息采集"), false);
  assert.equal(html.includes("/api/wechat-collector/cc-connect/"), false);
  assert.equal(html.includes("Homebrew"), false);
  assert.equal(html.includes('id="wechatCcConnectStatus"'), false);
  assert.equal(html.includes("renderWechatCcConnectStatus"), false);
  assert.equal(html.includes("copyWechatCcConnectCommand"), false);
  assert.ok(html.includes('id="wechatLlmEnabled"'));
  assert.ok(html.includes('id="wechatLlmProvider"'));
  assert.ok(html.includes('<option value="qwen">千问'));
  assert.ok(html.includes('id="wechatLlmApiKey"'));
  assert.ok(html.includes('id="loadWechatLlmModelsBtn"'));
  assert.ok(html.includes('id="saveWechatLlmConfigBtn"'));
  assert.ok(html.includes("renderWechatLlmConfig"));
  assert.ok(html.includes("renderWechatLlmModelOptions"));
  assert.ok(html.includes("loadWechatLlmModels"));
  assert.ok(html.includes("collectWechatLlmConfig"));
  assert.ok(html.includes('apiKey: wechatLlmApiKey.value.replace(/\\s+/g, "")'));
  assert.ok(html.includes("/api/wechat-collector/llm/models"));
  assert.ok(html.includes("apiKeyConfigured"));
  assert.ok(html.includes("1. 配置微信群"));
  assert.ok(html.includes("2. 运行监控"));
  assert.ok(html.includes("3. 排障日志"));
  assert.ok(html.includes("配置备份与恢复"));
  assert.ok(html.includes("附件只在本群最近一次采集中按可见文件名关联"));
  assert.ok(html.includes("staticPage(\"system-config\", systemConfigView, loadWechatCollector"));
  assert.ok(html.includes("renderWechatPipelineSmoke(statusData.pipelineSmoke || {})"));
  assert.ok(html.includes("const freshnessText = result.ok ? (result.fresh ? \"有效\" : (result.stale ? \"已过期\" : \"待确认\")) : \"未通过\";"));
  assert.ok(html.includes("完成：${formatTaskTime(result.finishedAt)}"));
  assert.ok(html.includes("skipped_interval"));
  assert.ok(html.includes("no_new_messages"));
  assert.ok(html.includes("captureMode"));
  assert.ok(html.includes("screenshotPath"));
  assert.ok(html.includes("captureRect"));
  assert.equal(html.includes('data-wechat-field="incremental_source"'), false);
  assert.equal(html.includes('data-wechat-field="cc_connect_chat_id"'), false);
  assert.equal(html.includes('data-wechat-action="fill-chat-id"'), false);
  assert.equal(html.includes("ccConnectLastMessageId"), false);
  assert.ok(html.includes("采集：OCR 可见窗口"));
  assert.ok(html.includes("采集方式：OCR 当前窗口/定时可见窗口"));
  assert.ok(html.includes("截图区域：${safeText(group.captureRect)}"));
  assert.ok(html.includes("ocrCommand"));
  assert.ok(html.includes("nextRunAt"));
  assert.ok(html.includes("附件候选：${Number(group.attachmentCandidateCount || 0)} · 已关联：${Number(group.attachmentCount || 0)}"));
  assert.ok(html.includes("附件过滤"));
  assert.ok(html.includes("installWechatCollectorService"));
  assert.ok(html.includes("uninstallWechatCollectorService"));
  assert.ok(html.includes("installWechatCollectorAutomation"));
  assert.ok(html.includes("uninstallWechatCollectorAutomation"));
  assert.ok(html.includes("confirmWechatSideEffect"));
  assert.ok(html.includes("会激活微信"));
  assert.ok(html.includes("LaunchAgent"));
  assert.ok(html.includes("runWechatCollectorOnce"));
  assert.ok(html.includes("runWechatCollectorGroupOnce"));
  assert.ok(html.includes("saveWechatCollectorGroup"));
  assert.ok(html.includes("groupName"));
  assert.ok(html.includes("await loadWechatCollector()"));
  assert.ok(html.includes("dryRunWechatCollector"));
  assert.ok(html.includes("showWechatGroupAttachmentStatus"));
  assert.ok(html.includes("runWechatPipelineSmoke"));
  assert.ok(html.includes("/api/wechat-collector/pipeline-smoke-test"));
  assert.ok(html.includes("fetchWechatPipelineSmoke"));
  assert.ok(html.includes("return { httpOk: response.ok, status: response.status, data };"));
  assert.ok(html.includes("renderWechatPipelineSmoke(result.data?.result || { ok: false, error: result.data?.error ||"));
  assert.ok(html.includes("/api/wechat-collector/dry-run"));
  assert.ok(html.includes("installWechatCollectorScheduler"));
  assert.ok(html.includes("uninstallWechatCollectorScheduler"));
  assert.ok(html.includes("collectWechatCollectorConfig"));
  assert.ok(html.includes("validateWechatCollectorConfig"));
  assert.ok(html.includes("wechatIntervalInputValue"));
  assert.equal(html.includes("Number(group.interval_minutes || 15)"), false);
  assert.equal(html.includes('value("interval_minutes") || "15"'), false);
  assert.ok(html.includes("采集间隔必须是大于等于 1 的整数"));
  assert.ok(html.includes("微信群名称重复"));
  assert.ok(html.includes("removeWechatCollectorRow"));
  assert.ok(html.includes("/api/wechat-collector/config"));
  assert.ok(html.includes("/api/wechat-collector/status"));
  assert.ok(html.includes('method: "PUT"'));
  assert.ok(html.includes("result.backupPath"));
  assert.ok(html.includes("已备份上一版配置"));
  assert.ok(html.includes("await loadWechatCollector()"));
  assert.ok(html.includes("${label}已保存，正在刷新状态"));
});
